services:
  - type: web
    name: ofzn-control-panel
    env: node
    plan: free
    buildCommand: |
      cd web && npm ci && npm run build && cd ../server && npm ci && node scripts/init-db.js
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
